<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/* 
 * Pagination Config Bootstrap 3 CSS Style
 * harviacode.com
 */

$config['query_string_segment'] = 'start';

$config['full_tag_open'] = '<nav><ul class="pagination" style="display: flex;padding-left: 0;list-style: none;border-radius: 0.25rem;margin: 20px 0;margin-top:0px;">';
$config['full_tag_close'] = '</ul></nav>';

$config['first_link'] = 'First';
$config['first_tag_open'] = '<li style="z-index: 2;color: #23527c;background-color: white;border:1px solid #ddd;padding:8px;">';
$config['first_tag_close'] = '</li>';

$config['last_link'] = 'Last';
$config['last_tag_open'] = '<li style="z-index: 2;color: #23527c;background-color: white;border:1px solid #ddd;padding:8px;border-top-right-radius: 4px;">';
$config['last_tag_close'] = '</li>';

$config['next_link'] = 'Next';
$config['next_tag_open'] = '<li style="z-index: 2;color: #23527c;background-color: white;border:1px solid #ddd;padding:8px;">';
$config['next_tag_close'] = '</li>';

$config['prev_link'] = 'Prev';
$config['prev_tag_open'] = '<li style="z-index: 2;color: #23527c;background-color: white;border:1px solid #ddd;padding:8px;    border-top-left-radius: 4px;">';
$config['prev_tag_close'] = '</li>';

$config['cur_tag_open'] = '<li class="active" style="z-index: 2;color: white;background-color: #00c0ef;;border:1px solid #00c0ef;;;padding:8px;"><a>';
$config['cur_tag_close'] = '</a></li>';

$config['num_tag_open'] = '<li style="z-index: 2;color: #23527c;background-color: white;border:1px solid #ddd;padding:8px;">';
$config['num_tag_close'] = '</li>';


/* End of file pagination.php */
/* Location: ./application/config/pagination.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-01-29 14:40:22 */
/* http://harviacode.com */