<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class About_header extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('About_header_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'about_header/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'about_header/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'about_header/index.html';
            $config['first_url'] = base_url() . 'about_header/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->About_header_model->total_rows($q);
        $about_header = $this->About_header_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'about_header_data' => $about_header,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('about_header/about_header_list', $data);
    }

    public function read($id) 
    {
        $row = $this->About_header_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'background_image' => $row->background_image,
	    );
            $this->load->view('about_header/about_header_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('about_header'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('about_header/create_action'),
	    'id' => set_value('id'),
	    'background_image' => set_value('background_image'),
	);
        $this->load->view('about_header/about_header_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'background_image' => $this->input->post('background_image',TRUE),
	    );

            $this->About_header_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('about_header'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->About_header_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('about_header/update_action'),
		'id' => set_value('id', $row->id),
		'background_image' => set_value('background_image', $row->background_image),
	    );
            $this->load->view('about_header/about_header_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('about_header'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'background_image' => $this->input->post('background_image',TRUE),
	    );

            $this->About_header_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('about_header'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->About_header_model->get_by_id($id);

        if ($row) {
            $this->About_header_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('about_header'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('about_header'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('background_image', 'background image', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file About_header.php */
/* Location: ./application/controllers/About_header.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-01-02 15:21:49 */
/* http://harviacode.com */